[package]
name = "libprovision"
version = "0.1.0"
edition = "2024"

[lib]
name = "libprovision"
path = "src/lib.rs"

[dependencies]
tonic = "0.13.1"
prost = "0.13"

[build-dependencies]
tonic-build = "*"