version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: "$POSTGRES_USER.db"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres

volumes:
  postgres: